/** Declaration file generated by dts-gen */

export function createClass(...args: any[]): Class<GeneratedClass>;

export function createContainer(...args: any[]): Class<Container>;

export function resolveContainer(Container: any): Container;

export namespace createClass {
    const name: string;

}

export namespace createContainer {
    const name: string;
}

export namespace resolveContainer {
    const name: string;
}

export class Container {
  constructor();

  getDeps(container: Container) : any;
  register(container: Container) : any;
  get(name: string): any;
}

export class GeneratedClass {
  constructor(...args: any[]);
}
